SELECT pg_get_viewdef('nome_da_view', true);

SELECT pg_get_viewdef('view_total_horas', true);

SELECT pg_get_viewdef('view_total_horas_mes', true);

CREATE VIEW view_total_horas AS
SELECT sum(rp.total_horas) AS total_horas_traba,
    sum(rp.total_horas_extra_dia) AS total_horas_extras,
    rp.nome_ref,
    f.nome,
    f.funcao
   FROM registro_ponto rp
     JOIN funcionario f ON rp.nome_ref = f.id
  GROUP BY rp.nome_ref, f.nome, f.funcao;

| pg_get_viewdef                                                                                                                   |
  
|
| view_total_horas_mes
|
create view view_total_horas_mes as
select
  app_data.nome,
  sum(app_data.hora_extra) as total_horas_extras_mes
from
  app_data
group by
  app_data.nome;


|
|SELECT pg_get_functiondef('update_hours'::regproc);
|

|
| Criando table app_data
|
create table public.app_data (
  id bigint generated always as identity not null,
  created_at timestamp with time zone null default now(),
  nome text null,
  horario_inicio time without time zone null,
  horario_saiu time without time zone null,
  hora_total interval null,
  hora_extra interval null,
  constraint app_data_pkey primary key (id)
) TABLESPACE pg_default;

create trigger calculate_hours BEFORE INSERT
or
update on app_data for EACH row
execute FUNCTION update_hours ();


|
| update_hours()
|
CREATE OR REPLACE FUNCTION public.update_hours()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.hora_total := NEW.horario_saiu - NEW.horario_inicio;
    IF NEW.hora_total > interval '8 hours' THEN
        NEW.hora_extra := NEW.hora_total - interval '8 hours';
    ELSE
        NEW.hora_extra := interval '0';
    END IF;
    RETURN NEW;
END;
$function$

|
| function calculate_hours()
|
    
CREATE OR REPLACE FUNCTION public.calculate_hours()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Calculate total hours
  IF NEW.inicio_dia IS NOT NULL AND NEW.saida IS NOT NULL THEN
    NEW.total_horas := (NEW.saida - NEW.inicio_dia) - (NEW.retorno - NEW.almoco);
  END IF;

  -- Calculate extra hours assuming 8 hours is the standard workday
  IF NEW.total_horas IS NOT NULL THEN
    NEW.hora_extra := NEW.total_horas - interval '8 hours';
    IF NEW.hora_extra < interval '0 hours' THEN
      NEW.hora_extra := interval '0 hours';
    END IF;
  END IF;

  RETURN NEW;
END;
$function$

|
| registro
|

create table public.registro (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data_registro date null,
  inicio_dia time without time zone null,
  almoco time without time zone null,
  retorno time without time zone null,
  saida time without time zone null,
  total_horas interval null,
  hora_extra interval null,
  user_ref bigint null,
  constraint registro_pkey primary key (id),
  constraint registro_user_ref_fkey foreign KEY (user_ref) references funcionario (id)
) TABLESPACE pg_default;

create trigger calculate_hours_trigger BEFORE INSERT
or
update on registro for EACH row
execute FUNCTION calculate_hours ();
